// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file - run 'make proto' to generate actual protobuf code

package proto

import (
	"context"

	"google.golang.org/protobuf/types/known/wrapperspb"
)

// Stub types - replace with actual generated code
type VideoServiceServer interface {
	UploadVideo(ctx context.Context, req *UploadVideoRequest) (*VideoResponse, error)
	GetVideo(ctx context.Context, req *GetVideoRequest) (*VideoResponse, error)
	GetUserVideos(ctx context.Context, req *GetUserVideosRequest) (*GetUserVideosResponse, error)
	UpdateVideo(ctx context.Context, req *UpdateVideoRequest) (*VideoResponse, error)
	DeleteVideo(ctx context.Context, req *DeleteVideoRequest) (*DeleteVideoResponse, error)
	GetTrendingVideos(ctx context.Context, req *GetTrendingVideosRequest) (*GetTrendingVideosResponse, error)
	RecordView(ctx context.Context, req *RecordViewRequest) (*RecordViewResponse, error)
}

type UnimplementedVideoServiceServer struct{}

type UploadVideoRequest struct {
	Title           string
	Description     string
	VideoData       []byte
	ThumbnailData   []byte
	DurationSeconds int32
	Width           int32
	Height          int32
}

type VideoResponse struct {
	VideoId         string
	UserId          string
	Title           string
	Description     string
	VideoUrl        string
	ThumbnailUrl    string
	DurationSeconds int32
	Width           int32
	Height          int32
	EncodingStatus  string
	ViewCount       int64
	LikeCount       int64
	CommentCount    int64
	ShareCount      int64
	CreatedAt       int64
}

type GetVideoRequest struct {
	VideoId string
}

type GetUserVideosRequest struct {
	UserId string
	Limit  int32
	Offset int32
}

type GetUserVideosResponse struct {
	Videos []*VideoResponse
	Total  int32
}

type UpdateVideoRequest struct {
	VideoId       string
	Title         *wrapperspb.StringValue
	Description   *wrapperspb.StringValue
	IsPublic      *wrapperspb.BoolValue
	AllowComments *wrapperspb.BoolValue
	AllowDuet     *wrapperspb.BoolValue
	AllowStitch   *wrapperspb.BoolValue
}

type DeleteVideoRequest struct {
	VideoId string
}

type DeleteVideoResponse struct {
	Success bool
}

type GetTrendingVideosRequest struct {
	Limit int32
}

type GetTrendingVideosResponse struct {
	Videos []*VideoResponse
}

type RecordViewRequest struct {
	VideoId string
}

type RecordViewResponse struct {
	Success bool
}

func RegisterVideoServiceServer(s interface{}, srv VideoServiceServer) {}
